# config/routes.yaml
route_product:
  path: /product/
  controller: App\Controller\ProductController::index
route_cart:
  path: /cart/
  controller: App\Controller\CartController::index
route_register:
  path: /register/
  controller: App\Controller\RegistrationController::register
route_login:
  path: /login/
  controller: App\Controller\SecurityController::login
app_logout:
  path: /logout
  methods: GET
index:
  path: /
  controller: App\Controller\DefaultController::index